### ISSUE TITLE
When rebuilding allow the user the option to "clear all" existing files and folders

### ISSUE THREAD

**Issue by jknowles** [wbuchanan/eda#19]
When rebuilding an eda report the user is prompted to enter `y or n` for deleting each existing file in the `/graphs` and `/tables` subdirectories. If you previously built a large EDA report on many variables this can result in needing user input hundreds of time before the report rebuilds. 

Consider this example:

```Stata
sysuse auto
eda, o("eda-report") root("./")
```

Then:

```
clear
sysuse auto
eda price mpg weight, o("eda-report") root("./") compile rebuild
```

**Comment by wbuchanan** [comment]
@jknowles,

I'm going to close this issue in this repository and move it to the repository with the function that is responsible for this behavior: https://github.com/wbuchanan/dirfile/issues/3.
