### ISSUE TITLE
varlist not allowed r(101)

### ISSUE THREAD

**Issue by jcalebsmith** [wbuchanan/eda#23]
I'm attempting to run the program in Stata/MP 16.1. I keep getting the "varlist not allowed" error.

. eda, o("eda-report") root("./")
varlist not allowed
r(101);

. eda, o("eda-report") root("C:\Desktop\")
varlist not allowed
r(101);

. eda price mpg weight, o("eda-report-small") root("./")
varlist not allowed
r(101);

I'm using the "auto" data, which is loading fine. All dependencies listed in the ReadMe have been installed.

**Comment by wbuchanan** [comment]
@jcalebsmith 
How did you install `eda` and which version are you running?  I've not encountered that specific error and recently ran some tests in a different platform that executed without a problem so I'm wanting to make sure it isn't a versioning issue.

**Comment by jcalebsmith** [comment]
@wbuchanan 
I first ran 
net inst eda, from(http://wbuchanan.github.io/eda)

Then ran
ssc install tuples
ssc install spineplot
ssc install estout
ssc install brewscheme

EDIT: I neglected to mention this originally, but I appear to using version 0.0.5 according to the ado file

I just ran "ado update" to make sure all the packages were up-to-date and I did see something unexpected with brewscheme:

brewscheme at http://fmwww.bc.edu/repec/bocode/b:
        package no longer available

I don't think that should impact the current error I'm seeing since the package is already installed on my computer, but odd that the package is listed as no longer available.

**Comment by wbuchanan** [comment]
@jcalebsmith 
So, I'd try uninstalling the copy of `brewscheme` from the SSC archive and use:

`net install brewscheme, from("https://wbuchanan.github.io/brewscheme")`

instead.  It isn't clear where the error was caused from, but I do know that that was one of the differences from the script that I recently used to test how things ran using [Galileo](https://galileoapp.io).  If that works to solve things let me know and I'll definitely make a note to update the README to not reference the SSC distribution of `brewscheme`.

**Comment by jcalebsmith** [comment]
@wbuchanan 

Confirmed! That was the issue. Uninstalling brewscheme and then re-installing with the command you provided fixed the issue. Thanks much for your help.

**Comment by wbuchanan** [comment]
@jcalebsmith 
Glad I was able to help and that we identified the issue.  I'll add an update to the README.
