### ISSUE TITLE
Enhancement: Ability to include/exclude specific graph types

### ISSUE THREAD

**Issue by jcalebsmith** [wbuchanan/eda#24]
I've attempted to run the program on data containing 120 continuous variables. The resulting .tex contains so many graphs that I'm unable to compile it into a PDF due to size constraints. In this particular case I'm primarily interested in the histograms + transformations, Q-Q plots, and correlation heatmap. I'm not interested in the scatter plots, for instance. 

The program allows one to include a subset of available variables, it would be really nice if we could include only a subset of the available graph types as well (or, alternatively, exclude certain graph types). This would reduce processing time and output size.

**Comment by wbuchanan** [comment]
There are options available to turn off different types of graphs.  For example, if you add `noscatter` to the options when calling the program it will not produce any scatter plots.

**Comment by jcalebsmith** [comment]
This is exactly what I was looking for. Thanks
