### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by ian-adams** [wbuchanan/eda#6]
Hello --

Probably my own lack of experience, but I can not figure out how to install the eda package in Stata. The "normal" way I use (ssc install eda) doesn't find the package. Can you point me to installation instructions?

**Comment by wbuchanan** [comment]
@iadams78 
The installation instructions are now in the README and I've copied them below as well.

```Stata
net inst eda, from(http://wbuchanan.github.io/eda)
```

Let me know if you have any issues with it.

**Comment by wbuchanan** [comment]
As a quick FYI, I am also going to add the install instructions to the slide deck from the Stata conference this year to make it easier for others as well.
