### ISSUE TITLE
Errors of "varlist not allowed"

### ISSUE THREAD

**Issue by MatixR** [wbuchanan/eda#7]
<img width="583" alt="screen shot 2018-09-28 at 11 57 35 pm" src="https://user-images.githubusercontent.com/4262777/46219614-5be59880-c37a-11e8-8da5-10365e8906c0.png">

I have tried many times , but still does not work  even with a subset of variables. 

I have no idea about it, please show me.  thanks

**Comment by wbuchanan** [comment]
@MatixR
Can you run the command again but add these two lines prior to the eda command:

set tracedepth 2
set trace on

**Comment by MatixR** [comment]
@wbuchanan  Thank you for your quick reply!
The following is the result  after  my adding the above two lines:

<img width="1109" alt="screen shot 2018-09-29 at 7 23 32 pm" src="https://user-images.githubusercontent.com/4262777/46245324-8b4de100-c41e-11e8-84a3-2dda0988520b.png">

And I also want to show you my "log.txt" . 
[2018_eda_stata_Main_logs.txt](https://github.com/wbuchanan/eda/files/2430593/2018_eda_stata_Main_logs.txt)

thanks again ~

**Comment by wbuchanan** [comment]
@MatixR 
Which version of `eda` are you using and can you also let me know which version of `dirfile` you are using?

```
which eda
which dirfile
```

**Comment by MatixR** [comment]
@wbuchanan 

I believe I am using the latest version of "eda" and "dirfile".

By the way the program is operating on Mac OS.



<img width="499" alt="screen shot 2018-09-30 at 6 24 37 pm" src="https://user-images.githubusercontent.com/4262777/46256550-ce6f8900-c4de-11e8-8f01-edbc075a1de6.png">

**Comment by MatixR** [comment]
@wbuchanan 

Hi, I get the reason why I fails:
[Screen Shot 2018-09-30 at 6.33.28 PM copy.pdf](https://github.com/wbuchanan/eda/files/2431468/Screen.Shot.2018-09-30.at.6.33.28.PM.copy.pdf)
<img width="1065" alt="screen shot 2018-09-30 at 6 33 28 pm" src="https://user-images.githubusercontent.com/4262777/46256894-cd8d2600-c4e3-11e8-838f-c0416fbf2966.png">

Replace the "dirfile.ado" with the latest one  on your github.
The bug is  fixed.

**Comment by wbuchanan** [comment]
@MatixR
Do you have an older copy of `brewscheme` on your machine?  If you look at the contents of `eda.pkg` on the gh-pages branch you’ll notice that `dirfile.ado` is not listed.  `eda` checks for a few dependencies and installs them internally so my best guess is that you have `dirfile` installed from a different package and it is an older version.

**Comment by wbuchanan** [comment]
@MatixR 
I'm running things again from a remote machine and will paste a copy of the log file to this comment once `eda` finishes running, but it seems like it is related to having an older copy of `dirfile` on your system.  I'll remove it from the repository to avoid confusion for others moving forward.

**Comment by MatixR** [comment]
@wbuchanan 

Thank for your help. I think I have older copy of brewscheme  on my machine!   Therefore, the "dirfile" is an old copy. 

By the way, your eda package do help a lot for understanding the data.

**Comment by wbuchanan** [comment]
@MatixR
Glad I was able to help and that you’ve found the package useful.
