### ISSUE TITLE
"Varlist not allowed"

### ISSUE THREAD

**Issue by ian-adams** [wbuchanan/eda#8]
Hello again Mr. Buchanan!

Thank you for updating the installation instructions. Sorry to be a bother, usually I'm able to get through Stata relatively easily, but eda is stumping me. Even when using the "minimal example" in the documentation, I get the same error over and over: 
varlist not allowed
r(101);

When using my own data, I use the minimal command, and get the same resulting error:
eda, r("C:\Users\adams\Google Drive\STATA Data\Officer Wellness") o("testing") comp

I have a feeling this might be related to how I'm pointing to the directory, but I've tried every variation with and without quotation marks, and nothing seems to be making a difference. Any ideas?

**Comment by wbuchanan** [comment]
Do you have an older version of `brewscheme` installed on your machine?  Typically this error has been related to an older version of `dirfile` that is part of brewscheme.  If you look at the closed issues it might help provide more detail (someone else reported a similar issue very recently).

**Comment by ian-adams** [comment]
That very well could be, I'll try that!

**Comment by ian-adams** [comment]
Thank you that worked perfectly, for some reason I had two old versions of
brewscheme installed. It's running right now finally. Thank you for all
your work.

**Comment by wbuchanan** [comment]
Not a problem; glad I could help.
