### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by ian-adams** [wbuchanan/eda#9]
Hello (again),

Was able to get eda to run on a small set of 17 variables (when I try to run  the full set of ~30, I get a memory error before the package completes). 

Issue: At the completion of the package, there was no report compiled, just a big folder of graphs. The last output from the package was: 

> (note: file C:/Users/adams/Google Drive/STATA Data/Officer Wellness/UDCeda_stuff/latent_only/makeLaTeX.bat not found)

Is there a command to run the compile without running through the entire .do file again? I checked the closed issues and don't see this referenced. Is there something I need to do to have subsequent runs compile automatically?

Thank you,
Ian

**Comment by wbuchanan** [comment]
@iadams78 
Do you have LaTeX on your Path?  And can you send the syntax that you used?  How much memory do you have on the computer running the program?  I've run it using a MacBook Pro with 16G of RAM and a few windows machines with more and less RAM without too much difficulty (there was one time where I ran into a memory error, but there were hundreds of variables in the file).

**Comment by ian-adams** [comment]
@wbuchanan 

Yes, I thought the memory error was weird, I'm using a less than a year old HP with 16GB of RAM on an I7 intel chipset. 

The syntax I used when memory ran out: 
> eda, r(C:\Users\adams\Google Drive\STATA Data\Officer Wellness\UDCeda_stuff\second_try) o("UDC_eda") comp scheme(538) perc authorname("Ian Adams") reportname("Utah Department of Corrections") 

Figuring it was too many variables, I cut the dataset down to just some latents, and got rid of ladder and pie charts I wasn't going to need, using the syntax:

> eda, r(C:\Users\adams\Google Drive\STATA Data\Officer Wellness\UDCeda_stuff\latent_only) o("UDC_eda") comp scheme(538) perc noladderplots nopiecharts 

That at least allowed the package to run in full, but no "report' was created, just gave me a folder full of charts. The "tables" subfolder created by the package has three .tex files in it - descriptives, higherorder, and orderstats. Within the \latent_only folder, it created a makeLatex.bat file, and a UDC_eda.tex file. 

A sub-question, maybe better for a separate issue thread, is that when the package fails to complete, trying to run the same command again errors out, I think because it's seeing the .tex file? I have to shut down Stata completely at that point, manually delete the offending file, and then it will run again.

**Comment by wbuchanan** [comment]
That sounds like not a whole lot of tables if there were 30 or so variables (unless they are or mostly all continuous).  What do you see in the makeLatex.bat file and are you able to run it from the windows command line?

**Comment by ian-adams** [comment]
Yeah, they probably look continuous to the package, they are additive composites from several ordinal observed variables.

The .bat file contents:

> ::Batch file to compile LaTeX source
pdflatex.exe "C:/Users/adams/Google Drive/STATA Data/Officer Wellness/UDCeda_stuff/latent_only/UDC_eda.tex"
pdflatex.exe "C:/Users/adams/Google Drive/STATA Data/Officer Wellness/UDCeda_stuff/latent_only/UDC_eda.tex"
pdflatex.exe "C:/Users/adams/Google Drive/STATA Data/Officer Wellness/UDCeda_stuff/latent_only/UDC_eda.tex"
DEL "C:\Users\adams\Google Drive\STATA Data\Officer Wellness\UDCeda_stuff\latent_only\UDC_eda.aux"
DEL "C:\Users\adams\Google Drive\STATA Data\Officer Wellness\UDCeda_stuff\latent_only\UDC_eda.lof"
DEL "C:\Users\adams\Google Drive\STATA Data\Officer Wellness\UDCeda_stuff\latent_only\UDC_eda.log"
DEL "C:\Users\adams\Google Drive\STATA Data\Officer Wellness\UDCeda_stuff\latent_only\UDC_eda.lot"
DEL "C:\Users\adams\Google Drive\STATA Data\Officer Wellness\UDCeda_stuff\latent_only\UDC_eda.out"
DEL "C:\Users\adams\Google Drive\STATA Data\Officer Wellness\UDCeda_stuff\latent_only\UDC_eda.toc"

When I run from the command line directly, it gives a series of errors, starting with:

> 'pdflatex.exe' is not recognized as an internal or external command,
operable program or batch file.

...and then says the same for each of the files w/i the .bat file. I'm not seeing any of the files it's looking for within the folder.

**Comment by wbuchanan** [comment]
That seems like it is an issue with LaTeX not being located on your path.  In the system settings in Windows you can edit/modify the environmental variables.  You'll just need to add the directory with the LaTeX binaries (or possibly the binaries themselves) to the PATH variable and then it should be fine.  On *nix based environments it is a little bit easier to work with since the default installation location for all the binaries is already included in the path.

**Comment by ian-adams** [comment]
Please bear with me here (you're so patient, thank you) --  So in the Stata command to run the eda package, I need to add the option "path(directory here)" ?

**Comment by wbuchanan** [comment]
@iadams78 
Now you're asking the difficult questions.  Let me go check out the documentation before I fully respond (and now others can see the benefit of commenting and documenting code playing out in a real world example like when you don't remember what the option in the command you programmed does anymore).

**Comment by wbuchanan** [comment]
@iadams78 
Found it.  So you would pass the location of the pdflatex binary to the `pdflatex()` option.  Basically, you'll want to put everything up to the `.exe` into that parameter.  It gets passed to `maketexcomp.ado` and if it isn't an empty string it will append the `.exe` if being called on a windows machine and write the full path into the batch file.

**Comment by ian-adams** [comment]
So, you know how sometimes an error is WAY simpler than the solutions you keep trying?  Please forgive my lack of knowledge, but I think I figured it out. Seems like you need to have Latex installed on your system.

I didn't realize Latex was a whole separate program, and that's my bad; I just thought it was some other dependency that the eda package installed. Once you started talking about a pdflatex binary, I did some thinking, found that I needed to install Latex, etc. Once I did that, I was able to run the batch file from the command line. It created a very nice 1100+ page pdf. 

I'm very appreciative of your help! I'm not sure if the TSTO addition of "install Latex" in the help file would be appropriate, since that seems like something everyone else knows. I'll go back to trying to run the package past the memory errors I was getting before, maybe it has something to do with the same thing.

Thank you!

**Comment by wbuchanan** [comment]
If one person is unclear about something, there are almost definitely other people who are also unclear about the same thing.  I definitely don’t mind adding a reminder to the helpfiles/README to install LaTeX first.  Thanks for the suggestion.
